export const FETCH_MOVIES = "FETCH_MOVIES";
export const SET_MOVIES_TO_STATE = "SET_MOVIES_TO_STATE";

export const ADD_MOVIE = "ADD_MOVIE";
export const SET_NEW_MOVIE_TO_STATE = "SET_NEW_MOVIE_TO_STATE";

export const REMOVE_MOVIE = "REMOVE_MOVIE";
export const SET_REMOVE_MOVIE_TO_STATE = "SET_REMOVE_MOVIE_TO_STATE";

export const SEARCH_MOVIE = "SEARCH_MOVIE";

export const UPDATE_MOVIE = "UPDATE_MOVIE";
export const SET_UPDATED_MOVIE_TO_STATE = "SET_UPDATED_MOVIE_TO_STATE";
