export const FETCH_MOVIES = "FETCH_MOVIES";
export const SET_MOVIES_TO_STATE = "SET_MOVIES_TO_STATE";

export const REMOVE_MOVIE = "REMOVE_MOVIE";
export const SET_REMOVE_MOVIE_TO_STATE = "SET_REMOVE_MOVIE_TO_STATE";
