export const REPLENISH_BALANCE = "REPLENISH_BALANCE";
export const SET_BALANCE_TO_STATE = "SET_BALANCE_TO_STATE";

export const BUY_MOVIE = "BUY_MOVIE";
export const SET_BOUGHT_MOVIE_TO_STATE = "SET_BOUGHT_MOVIE_TO_STATE";

export const REMOVE_TICKET = "REMOVE_TICKET";
export const REMOVE_TICKET_FROM_STATE = "REMOVE_TICKET_FROM_STATE";
