export const REPLENISH_BALANCE = "REPLENISH_BALANCE";
export const SET_BALANCE_TO_STATE = "SET_BALANCE_TO_STATE";

export const BUY_MOVIE = "BUY_MOVIE";
export const SET_BOUGHT_MOVIE_TO_STATE = "SET_BOUGHT_MOVIE_TO_STATE";

export const CHANGE_USER_INFO = "CHANGE_USER_INFO";
export const SET_NEW_USER_INFO_TO_STATE = "SET_NEW_USER_INFO_TO_STATE";

export const REMOVE_TICKET = "REMOVE_TICKET";
export const REMOVE_TICKET_FROM_STATE = "REMOVE_TICKET_FROM_STATE";

export const REMOVE_ACCOUNT = "REMOVE_ACCOUNT";
export const SET_REMOVE_ACCOUNT_TO_STATE = "SET_REMOVE_ACCOUNT_TO_STATE";
