export const FETCH_USERS = "FETCH_USERS";
export const SET_USERS_TO_STATE = "SET_USERS_TO_STATE";

export const REMOVE_USERS = "REMOVE_USERS";
export const SET_REMOVE_USERS_TO_STATE = "SET_REMOVE_USERS_TO_STATE";
